(async()=>{
const app=document.querySelector('#app');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
document.head.insertAdjacentHTML('beforeend',`<style>
.pf23{min-height:100dvh;background:#f7f5ef;color:#29251f;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.pf23 *{box-sizing:border-box}.pf23 .topbar{height:86px;display:flex;align-items:center;justify-content:space-between;padding:18px 20px;background:#faf8f2;border-bottom:1px solid #e8e1d8}.pf23 .brand{display:flex;gap:12px;align-items:center}.pf23 .brand-mark{width:38px;height:38px;border:1px solid #a84e48;border-radius:50%;display:grid;place-items:center;color:#9b3e3a;font-weight:700}.pf23 .brand small{display:block;color:#77716a;margin-top:2px}.pf23 .icon-btn{border:0;background:#fff;border-radius:999px;width:38px;height:38px;box-shadow:0 8px 22px #0001}.pf23 .stage{height:clamp(390px,54dvh,620px);position:relative;overflow:hidden;background:#d7d4cc}.pf23 #viewer{position:absolute;inset:0}.pf23 canvas{display:block;touch-action:none}.pf23 .badge{position:absolute;left:18px;top:18px;padding:8px 12px;border-radius:999px;background:#fffffff2;box-shadow:0 12px 28px #0002;font-size:12px;color:#514b44}.pf23 .hint{position:absolute;left:50%;bottom:14px;transform:translateX(-50%);padding:8px 13px;border-radius:999px;background:#ffffffd9;color:#756e65;font-size:12px;white-space:nowrap}.pf23 .loading{position:absolute;inset:0;display:grid;place-items:center;text-align:center;padding:28px;color:#555;line-height:1.7}.pf23 .tabs{display:grid;grid-template-columns:repeat(4,1fr);height:62px;background:#fff;border-bottom:1px solid #e8e1d8}.pf23 .tabs button{border:0;background:#fff;color:#8a837b;font-size:15px}.pf23 .tabs button.active{color:#a84e48;border-bottom:2px solid #b34c47}.pf23 .panel{display:none;padding:24px 20px 34px}.pf23 .panel.active{display:block}.pf23 .section-heading{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:16px}.pf23 .section-heading small{color:#9e4b47;font-weight:800;letter-spacing:.18em;font-size:11px}.pf23 h2{font-size:25px;margin:6px 0 0}.pf23 .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.pf23 button.choice,.pf23 button.card{border:1px solid #e4ddd2;background:#fff;border-radius:8px;padding:13px;text-align:left;box-shadow:0 8px 20px #00000008}.pf23 button.active{outline:2px solid #b9514b}.pf23 button b,.pf23 button strong{display:block;font-size:15px}.pf23 button small{display:block;color:#8c847b;margin-top:5px}.pf23 .swatch{height:54px;border-radius:6px;margin-bottom:10px;background:var(--sw)}.pf23 .note{margin-top:14px;background:#fff;border-radius:8px;padding:13px;color:#5e574f}.pf23 .measurements{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.pf23 label{background:#fff;border-radius:8px;padding:12px;border:1px solid #e4ddd2}.pf23 label span{display:block;color:#756e65;margin-bottom:6px}.pf23 input{width:100%;border:0;background:#f3f0ea;border-radius:6px;padding:10px;font-size:17px}.pf23 .primary-btn{margin-top:14px;width:100%;height:48px;border:0;border-radius:8px;background:#9d4944;color:#fff;font-size:16px}
</style>`);
app.innerHTML=`<main class="pf23"><header class="topbar"><div class="brand"><span class="brand-mark">P</span><div><strong>PetForm V23</strong><small>稳定 WebGL 3D 版</small></div></div><button class="icon-btn" id="reset">↻</button></header><section class="stage"><div id="viewer"></div><div class="loading" id="loading">正在加载 WebGL 3D...</div><div class="badge" id="badge">小型犬白模 · WebGL</div><div class="hint">单指旋转 · 双指缩放 · 固定居中</div></section><nav class="tabs"><button class="active" data-tab="body">体型</button><button data-tab="wear">衣服</button><button data-tab="scene">场景</button><button data-tab="size">尺码</button></nav><section class="panel active" id="body"><div class="section-heading"><div><small>3D MANNEQUIN</small><h2>选择真实白模体型</h2></div><span>固定居中</span></div><div class="grid"><button class="choice active" data-breed="toy"><b>小型犬白模</b><small>圆头、垂耳、短身</small></button><button class="choice" data-breed="hound"><b>细犬白模</b><small>长腿、窄胸、长颈</small></button><button class="choice" data-breed="french"><b>法斗白模</b><small>宽胸、短背、立耳</small></button><button class="choice" data-breed="corgi"><b>柯基白模</b><small>长背、短腿、翘尾</small></button></div></section><section class="panel" id="wear"><div class="section-heading"><div><small>WARDROBE</small><h2>选择服装款式</h2></div><span id="fitBadge">推荐 M</span></div><div class="grid" id="clothGrid"></div><div class="note">这是 WebGL 3D：狗狗和衣服都在 3D 空间里旋转。</div></section><section class="panel" id="scene"><div class="section-heading"><div><small>SCENE</small><h2>切换场景背景</h2></div></div><div class="grid"><button class="card active" data-scene="studio"><span class="swatch" style="--sw:#d8d7d1"></span><b>摄影棚</b><small>灰底产品拍摄</small></button><button class="card" data-scene="home"><span class="swatch" style="--sw:#d9c7b0"></span><b>家庭客厅</b><small>暖色空间</small></button><button class="card" data-scene="grass"><span class="swatch" style="--sw:#afd0bd"></span><b>草坪户外</b><small>绿色户外</small></button><button class="card" data-scene="coffee"><span class="swatch" style="--sw:#a77f60"></span><b>咖啡馆</b><small>木色背景</small></button><button class="card" data-scene="shop"><span class="swatch" style="--sw:#dde3e6"></span><b>商场橱窗</b><small>冷灰陈列</small></button></div></section><section class="panel" id="size"><div class="section-heading"><div><small>MEASUREMENTS</small><h2>输入关键数值</h2></div></div><div class="measurements"><label><span>胸围</span><input id="chest" type="number" value="42"></label><label><span>背长</span><input id="back" type="number" value="32"></label><label><span>颈围</span><input id="neck" type="number" value="25"></label><label><span>肩高</span><input id="height" type="number" value="29"></label></div><button class="primary-btn" id="applyBtn">更新 3D 白模</button></section></main>`;
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
async function loadThree(){const urls=['https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://fastly.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://gcore.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://unpkg.com/three@0.160.0/build/three.module.js','https://esm.sh/three@0.160.0'];let last;for(const url of urls){try{$('#loading').textContent='正在加载：'+new URL(url).host;return await import(url)}catch(e){last=e}}throw last}
let THREE;try{THREE=await loadThree()}catch(e){$('#loading').innerHTML='WebGL 引擎加载失败。<br>请刷新或打开网络代理。';return}$('#loading').remove();
const viewer=$('#viewer'),scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-3.8,3.8,3,-3,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewer.appendChild(renderer.domElement);
const root=new THREE.Group(),dog=new THREE.Group(),setRoot=new THREE.Group();root.add(dog);scene.add(setRoot,root);camera.position.set(4,2.4,7);camera.lookAt(0,.85,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x8a8176,2.1));const key=new THREE.DirectionalLight(0xffffff,3.4);key.position.set(-3,6,5);key.castShadow=true;scene.add(key);const fill=new THREE.DirectionalLight(0xcfe0ff,1.2);fill.position.set(4,3,-4);scene.add(fill);
const mats={white:new THREE.MeshPhysicalMaterial({color:0xf4efe3,roughness:.5,clearcoat:.25}),nose:new THREE.MeshStandardMaterial({color:0x151515,roughness:.42}),eye:new THREE.MeshStandardMaterial({color:0x050505}),trim:new THREE.MeshStandardMaterial({color:0x2b2926,roughness:.55})};
const breeds={toy:{label:'小型犬白模',len:1,body:.95,leg:.85,head:1,ear:'drop'},hound:{label:'细犬白模',len:1.32,body:.78,leg:1.25,head:.84,ear:'fold'},french:{label:'法斗白模',len:.88,body:1.12,leg:.72,head:1.16,ear:'up'},corgi:{label:'柯基白模',len:1.28,body:.86,leg:.62,head:.95,ear:'up'}};
const clothes={none:['不穿衣服','#f4efe3'],stripe:['条纹毛衣','#efe8dd'],vest:['机能马甲','#31586a'],tee:['基础T恤','#e8dfd4'],rain:['防水雨衣','#e8ca2d'],puffer:['蓬蓬棉服','#b94b40'],hoodie:['连帽卫衣','#6c8796'],harness:['胸背背带','#202225'],dress:['裙摆衫','#dca6ba']};
let state={breed:'toy',cloth:'none',scene:'studio'},scale={len:1,body:1,leg:1,width:1},drag=false,lastX=0,pinch=0;
const sph=new THREE.SphereGeometry(1,64,32),cyl=new THREE.CylinderGeometry(1,1,1,48),cone=new THREE.ConeGeometry(1,1,48),torus=new THREE.TorusGeometry(1,.035,16,96),box=new THREE.BoxGeometry(1,1,1);
function mesh(g,m,p,s,r){const o=new THREE.Mesh(g,m);o.position.set(...p);o.scale.set(...s);if(r)o.rotation.set(...r);o.castShadow=o.receiveShadow=true;return o}
function mat(c,rough=.6){return new THREE.MeshStandardMaterial({color:c,roughness:rough})}
function buildDog(){dog.clear();const b=breeds[state.breed],L=b.len*scale.len,B=b.body*scale.body,W=scale.width,H=b.leg*scale.leg;dog.add(mesh(sph,mats.white,[0,.92,0],[1.25*L,.48*B,.42*W],[0,0,.02]),mesh(sph,mats.white,[.92*L,.95,0],[.55,.55*B,.48*W]),mesh(sph,mats.white,[-.98*L,.88,0],[.48,.46*B,.42*W]),mesh(cyl,mats.white,[1.25*L,1.36,0],[.2,.56,.2],[0,0,-.55]),mesh(sph,mats.white,[1.65*L,1.72,0],[.45*b.head,.38*b.head,.34*b.head]),mesh(sph,mats.white,[2.02*L,1.65,0],[.28*b.head,.18*b.head,.2*b.head]));dog.add(mesh(sph,mats.nose,[2.26*L,1.66,0],[.075,.055,.065]));[-1,1].forEach(z=>dog.add(mesh(sph,mats.eye,[1.78*L,1.82,z*.19],[.038,.038,.038])));leg(-.62*L,-.22*W,H,.92);leg(-.62*L,.22*W,H,1);leg(.72*L,-.22*W,H,.92);leg(.72*L,.22*W,H,1);ears(b,L);tail(b,L);garment(L,B,W);centerDog();$('#badge').textContent=breeds[state.breed].label+' · WebGL'}
function leg(x,z,H,s){dog.add(mesh(cyl,mats.white,[x,.46,z],[.13*s,.58*H,.13*s]));dog.add(mesh(sph,mats.white,[x+.03,.08,z],[.17*s,.08,.14*s]))}
function ears(b,L){[-1,1].forEach(z=>dog.add(b.ear==='up'?mesh(cone,mats.white,[1.58*L,2.1,z*.27],[.15,.45,.07],[z*.15,0,-.1]):mesh(sph,mats.white,[1.6*L,1.58,z*.3],[.12,.36,.07],[.45,0,z*.3])))}
function tail(b,L){dog.add(b.label.includes('法斗')?mesh(sph,mats.white,[-1.42*L,1.02,0],[.12,.08,.08]):mesh(torus,mats.white,[-1.5*L,1.18,0],[.9,.9,.62],[0,1.55,0]))}
function garment(L,B,W){if(state.cloth==='none')return;const color=clothes[state.cloth][1],m=new THREE.MeshPhysicalMaterial({color,roughness:state.cloth==='rain'?.25:.62,clearcoat:state.cloth==='rain'?.8:.08});const g=new THREE.Group();if(state.cloth==='harness'){g.add(mesh(torus,m,[.18*L,1.02,0],[.42,.06,.48*W],[0,1.57,0]),mesh(torus,m,[-.55*L,.9,0],[.5,.06,.44*W],[0,1.57,0]));dog.add(g);return}g.add(mesh(sph,m,[-.03*L,.96,0],[1.32*L,.52*B,.455*W]));g.add(mesh(torus,mats.trim,[1.0*L,1.32,0],[.27,.16,.36],[0,1.57,0]),mesh(torus,mats.trim,[-.35*L,.62,0],[.9*L,.12,.42*W],[0,1.57,0]));if(state.cloth==='stripe')for(let i=-3;i<4;i++)g.add(mesh(torus,mat(i%2?0xb8524e:0x263744),[i*.24*L,.97,0],[.42,.045,.47*W],[0,1.57,0]));if(state.cloth==='puffer')for(let i=-3;i<4;i++)g.add(mesh(torus,mat(0x8e302d),[i*.22*L,.98,0],[.4,.04,.47*W],[0,1.57,0]));if(state.cloth==='hoodie')g.add(mesh(sph,m,[1.08*L,1.48,0],[.36,.23,.34]));if(state.cloth==='dress')g.add(mesh(cone,m,[-.7*L,.55,0],[.72,.38,.47*W],[0,0,Math.PI]));dog.add(g)}
function centerDog(){dog.updateMatrixWorld(true);const box3=new THREE.Box3().setFromObject(dog),c=box3.getCenter(new THREE.Vector3()),s=box3.getSize(new THREE.Vector3());dog.position.x-=c.x;dog.position.y+=.92-c.y;dog.position.z-=c.z;root.scale.setScalar(clamp(3.6/Math.max(s.x,s.y*1.25),.82,1.35))}
function makeSet(){setRoot.clear();const colors={studio:0xd8d7d1,home:0xd9c7b0,grass:0xafd0bd,coffee:0xa77f60,shop:0xdde3e6};scene.background=new THREE.Color(colors[state.scene]||colors.studio);const floor=mesh(new THREE.PlaneGeometry(9,6),mat(state.scene==='grass'?0x6f9259:state.scene==='coffee'?0x6c4b36:state.scene==='home'?0xb99673:0xc9c8c0,.78),[0,-.02,-.4],[1,1,1],[-Math.PI/2,0,0]);floor.receiveShadow=true;setRoot.add(floor);setRoot.add(mesh(new THREE.CircleGeometry(1.4,96),new THREE.MeshBasicMaterial({color:0x000000,transparent:true,opacity:.13,depthWrite:false}),[0,.01,0],[1.8,.5,1],[-Math.PI/2,0,0]));if(state.scene==='studio'){setRoot.add(mesh(box,mat(0xefefeb),[-2.7,.58,-1.9],[1,1.1,1]));setRoot.add(mesh(new THREE.CylinderGeometry(.62,.62,.18,64),mat(0xf7f6f1),[2.3,.1,-1.5],[1,1,1]));}if(state.scene==='home'){setRoot.add(mesh(box,mat(0x8b654d),[-2.7,.45,-2.1],[2.2,.45,.6]));setRoot.add(mesh(sph,mat(0x3f7c4e),[2.7,.75,-1.2],[.45,.45,.45]));}if(state.scene==='shop'){for(let i=0;i<4;i++)setRoot.add(mesh(box,mat([0xb8483d,0x2f5361,0xe6c82f,0xdba6ba][i]),[-1.4+i*.85,1.55,-2.5],[.32,.45,.04]));}if(state.scene==='grass'){for(let i=0;i<42;i++)setRoot.add(mesh(cone,mat(i%2?0x4f7f3f:0x7b9a4e),[(Math.random()-.5)*6,.14,(Math.random()-.5)*3-1],[.02,.24,.02],[0,0,(Math.random()-.5)*.5]));}if(state.scene==='coffee'){setRoot.add(mesh(new THREE.CylinderGeometry(.55,.55,.07,48),mat(0x8f674b),[-2.5,.6,-1.6],[1,1,1]));setRoot.add(mesh(box,mat(0x4a3025),[0,1.8,-2.8],[5.8,1.8,.08]));}}
function apply(){const b=breeds[state.breed],ch=+chest.value,ba=+back.value,he=+height.value;scale={len:clamp(ba/32,.82,1.28),body:clamp(ch/42,.82,1.22),width:clamp(ch/42,.82,1.24),leg:clamp(he/29,.82,1.22)};$('#fitBadge').textContent='推荐 '+(ch<36?'S':ch<50?'M':ch<66?'L':'XL');buildDog()}
function layout(){const r=viewer.getBoundingClientRect(),aspect=r.width/r.height,span=3.45;camera.left=-span*aspect;camera.right=span*aspect;camera.top=span;camera.bottom=-span;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}
function animate(){requestAnimationFrame(animate);renderer.render(scene,camera)}
Object.entries(clothes).forEach(([k,v])=>$('#clothGrid').insertAdjacentHTML('beforeend',`<button class="card ${k==='none'?'active':''}" data-cloth="${k}"><span class="swatch" style="--sw:${v[1]}"></span><strong>${v[0]}</strong><small>${k==='none'?'查看白模':'WebGL 试穿'}</small></button>`));
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(n=>n.classList.toggle('active',n===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});$$('[data-breed]').forEach(b=>b.onclick=()=>{state.breed=b.dataset.breed;$$('[data-breed]').forEach(n=>n.classList.toggle('active',n===b));apply()});$$('[data-cloth]').forEach(b=>b.onclick=()=>{state.cloth=b.dataset.cloth;$$('[data-cloth]').forEach(n=>n.classList.toggle('active',n===b));buildDog()});$$('[data-scene]').forEach(b=>b.onclick=()=>{state.scene=b.dataset.scene;$$('[data-scene]').forEach(n=>n.classList.toggle('active',n===b));makeSet()});applyBtn.onclick=apply;reset.onclick=()=>{root.rotation.y=.25;camera.zoom=1;camera.updateProjectionMatrix()};const dom=renderer.domElement;dom.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;dom.setPointerCapture&&dom.setPointerCapture(e.pointerId)});dom.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX;lastX=e.clientX;root.rotation.y+=dx*.01});dom.addEventListener('pointerup',()=>drag=false);dom.addEventListener('pointercancel',()=>drag=false);dom.addEventListener('touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});dom.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);camera.zoom=clamp(camera.zoom+(d-pinch)*.004,.72,2.3);pinch=d;camera.updateProjectionMatrix()}},{passive:true});new ResizeObserver(layout).observe(viewer);makeSet();apply();root.rotation.y=.25;layout();animate();
})()