(async()=>{
const app=document.querySelector('#app');
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const css=document.createElement('style');
css.textContent=`
.pf26{min-height:100svh;background:#f7f4ed;color:#26221d;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.pf26 *{box-sizing:border-box}.pf26 .topbar{height:68px;display:flex;align-items:center;justify-content:space-between;padding:10px 18px;background:#fbf9f3;border-bottom:1px solid #e8dfd3}.pf26 .brand{display:flex;gap:11px;align-items:center}.pf26 .mark{width:34px;height:34px;border-radius:50%;border:1px solid #9d4742;display:grid;place-items:center;color:#9d4742;font-weight:800}.pf26 .brand small{display:block;color:#756f67;font-size:11px;margin-top:2px}.pf26 .icon{border:0;background:#fff;border-radius:999px;width:38px;height:38px;box-shadow:0 8px 24px #0001}.pf26 .stage{height:clamp(360px,53svh,575px);position:relative;overflow:hidden;background:#d2d0c9}.pf26 #viewer{position:absolute;inset:0}.pf26 canvas{display:block;touch-action:none}.pf26 .badge{position:absolute;left:18px;top:18px;padding:8px 12px;border-radius:999px;background:#fffffff0;box-shadow:0 14px 30px #0002;font-size:12px;color:#4d473f}.pf26 .hint{position:absolute;left:50%;bottom:12px;transform:translateX(-50%);padding:8px 13px;border-radius:999px;background:#ffffffdc;color:#716a62;font-size:12px;white-space:nowrap}.pf26 .tabs{display:grid;grid-template-columns:repeat(4,1fr);height:50px;background:#fff;border-bottom:1px solid #e8dfd3}.pf26 .tabs button{border:0;background:#fff;color:#8b837b;font-size:14px}.pf26 .tabs button.active{color:#a84e48;border-bottom:2px solid #b34c47}.pf26 .panel{display:none;padding:18px 18px 30px}.pf26 .panel.active{display:block}.pf26 .head{display:flex;justify-content:space-between;gap:14px;margin-bottom:15px}.pf26 .head small{color:#9e4b47;font-weight:800;letter-spacing:.18em;font-size:11px}.pf26 h2{font-size:22px;margin:6px 0 0}.pf26 .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.pf26 button.card{border:1px solid #e4dbcf;background:#fff;border-radius:8px;padding:12px;text-align:left;box-shadow:0 8px 20px #00000008}.pf26 button.active{outline:2px solid #b9514b}.pf26 button b{display:block;font-size:15px}.pf26 button small{display:block;color:#8c847b;margin-top:5px}.pf26 .sw{height:42px;border-radius:6px;margin-bottom:9px;background:var(--sw)}.pf26 label{display:block;background:#fff;border:1px solid #e4dbcf;border-radius:8px;padding:12px}.pf26 label span{display:block;color:#756e65;margin-bottom:6px}.pf26 input{width:100%;border:0;background:#f1ede6;border-radius:6px;padding:10px;font-size:16px}.pf26 .primary{margin-top:14px;width:100%;height:48px;border:0;border-radius:8px;background:#9d4944;color:#fff;font-size:16px}.pf26 .loading{position:absolute;inset:0;display:grid;place-items:center;text-align:center;color:#555;line-height:1.7;padding:30px}`;document.head.appendChild(css);
app.innerHTML=`<main class="pf26"><header class="topbar"><div class="brand"><span class="mark">P</span><div><strong>PetForm V26</strong><small>程序化解剖白模</small></div></div><button class="icon" id="reset">↻</button></header><section class="stage"><div id="viewer"></div><div class="loading" id="loading">正在生成真实感白模...</div><div class="badge" id="badge">小型犬 · 解剖白模</div><div class="hint">单指旋转 · 双指缩放 · 程序生成白模</div></section><nav class="tabs"><button class="active" data-tab="body">体型</button><button data-tab="wear">衣服</button><button data-tab="scene">场景</button><button data-tab="size">尺码</button></nav><section class="panel active" id="body"><div class="head"><div><small>ANATOMY MANNEQUIN</small><h2>犬类真实白模</h2></div><span>连续躯干</span></div><div class="grid"><button class="card active" data-breed="toy"><b>小型犬</b><small>圆颅、短吻、垂耳</small></button><button class="card" data-breed="hound"><b>细犬</b><small>深胸、收腹、长腿</small></button><button class="card" data-breed="french"><b>法斗</b><small>宽胸、短背、立耳</small></button><button class="card" data-breed="corgi"><b>柯基</b><small>长背、短腿、翘尾</small></button></div></section><section class="panel" id="wear"><div class="head"><div><small>WARDROBE</small><h2>立体服装壳</h2></div><span id="fit">推荐 M</span></div><div class="grid" id="clothGrid"></div></section><section class="panel" id="scene"><div class="head"><div><small>SCENE</small><h2>背景场景</h2></div></div><div class="grid"><button class="card active" data-scene="studio"><span class="sw" style="--sw:#d3d0c8"></span><b>摄影棚</b><small>产品级灰底</small></button><button class="card" data-scene="home"><span class="sw" style="--sw:#d9c7b0"></span><b>客厅</b><small>暖色家居</small></button><button class="card" data-scene="grass"><span class="sw" style="--sw:#a8c79f"></span><b>草坪</b><small>自然户外</small></button><button class="card" data-scene="shop"><span class="sw" style="--sw:#dce3e5"></span><b>商场</b><small>橱窗灯光</small></button></div></section><section class="panel" id="size"><div class="head"><div><small>MEASUREMENTS</small><h2>关键尺寸</h2></div></div><div class="grid"><label><span>胸围</span><input id="chest" type="number" value="42"></label><label><span>背长</span><input id="back" type="number" value="32"></label><label><span>颈围</span><input id="neck" type="number" value="25"></label><label><span>肩高</span><input id="height" type="number" value="29"></label></div><button class="primary" id="apply">更新白模</button></section></main>`;
async function loadThree(){const urls=['https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://fastly.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://gcore.jsdelivr.net/npm/three@0.160.0/build/three.module.js','https://unpkg.com/three@0.160.0/build/three.module.js'];let last;for(const u of urls){try{loading.textContent='加载 3D 引擎：'+new URL(u).host;return await import(u)}catch(e){last=e}}throw last}
let THREE;try{THREE=await loadThree()}catch(e){loading.innerHTML='3D 引擎加载失败，请刷新或开网络代理';return}loading.remove();
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const viewer=$('#viewer'),scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-3.4,3.4,3,-3,.1,100),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});
renderer.setPixelRatio(Math.min(devicePixelRatio||1,2.3));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewer.appendChild(renderer.domElement);camera.position.set(4.7,2.35,7.2);camera.lookAt(0,1.05,0);
scene.add(new THREE.HemisphereLight(0xffffff,0x8d8173,2.4));const key=new THREE.DirectionalLight(0xffffff,3.2);key.position.set(-4,6,5);key.castShadow=true;scene.add(key);const rim=new THREE.DirectionalLight(0xdfe8ff,1.4);rim.position.set(4,3,-4);scene.add(rim);
const root=new THREE.Group(),dog=new THREE.Group(),setRoot=new THREE.Group();root.add(dog);scene.add(setRoot,root);
const white=new THREE.MeshPhysicalMaterial({color:0xf1ead8,roughness:.47,clearcoat:.28,metalness:0});const dark=new THREE.MeshStandardMaterial({color:0x12110f,roughness:.45});const lineMat=new THREE.MeshStandardMaterial({color:0xdfd6c7,roughness:.7});
const breeds={toy:{label:'小型犬',L:1,W:1,H:.9,leg:.9,head:1,ear:'drop',tail:'up'},hound:{label:'细犬',L:1.38,W:.78,H:1.2,leg:1.25,head:.86,ear:'fold',tail:'straight'},french:{label:'法斗',L:.86,W:1.18,H:.78,leg:.72,head:1.16,ear:'up',tail:'nub'},corgi:{label:'柯基',L:1.35,W:.9,H:.72,leg:.62,head:.95,ear:'up',tail:'up'}};
const clothes={none:['不穿衣服','#efe8d8'],vest:['贴身马甲','#31586a'],tee:['柔软T恤','#e7ded2'],rain:['防水雨衣','#e6c62b'],puffer:['绗缝棉服','#b94b40'],harness:['胸背背带','#222']};let state={breed:'toy',cloth:'none',scene:'studio'},scale={L:1,W:1,H:1,leg:1};
function material(c,r=.58){return new THREE.MeshStandardMaterial({color:c,roughness:r})}
function add(g,m,p,s,r=[0,0,0],parent=dog){const o=new THREE.Mesh(g,m);o.position.set(...p);o.scale.set(...s);o.rotation.set(...r);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function bodyGeometry(L,W,H){const seg=34,rad=28,pos=[],idx=[];for(let i=0;i<=seg;i++){const t=i/seg,x=(t-.5)*2.55*L;const chest=Math.exp(-Math.pow((t-.34)/.2,2));const belly=Math.exp(-Math.pow((t-.62)/.18,2));const rump=Math.exp(-Math.pow((t-.8)/.18,2));const ry=(.38+.18*chest+.04*belly+.1*rump)*H;const rz=(.29+.16*chest-.04*belly+.08*rump)*W;const topline=.08*Math.sin((t-.1)*Math.PI);for(let j=0;j<rad;j++){const a=j/rad*Math.PI*2;const y=Math.sin(a)*ry+1.02+topline;const z=Math.cos(a)*rz;pos.push(x,y,z)}}for(let i=0;i<seg;i++)for(let j=0;j<rad;j++){const a=i*rad+j,b=i*rad+(j+1)%rad,c=(i+1)*rad+j,d=(i+1)*rad+(j+1)%rad;idx.push(a,c,b,b,c,d)}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.setIndex(idx);geo.computeVertexNormals();return geo}
function limb(x,z,front,b){const upper=front?.42:.48,lower=front?.42:.44,hip=front?1.04:1.0,knee=front?.55:.52,foot=.16;add(new THREE.CapsuleGeometry(.105*b.W,.28,10,20),white,[x,hip,z],[1,upper*b.leg,1],[0,0,front?.18:-.12]);add(new THREE.SphereGeometry(1,28,16),white,[x+(front?.04:-.04),knee,z],[.15,.13,.14]);add(new THREE.CapsuleGeometry(.085*b.W,.32,10,20),white,[x+(front?.08:-.08),.31,z],[1,lower*b.leg,1],[0,0,front?-.04:.15]);add(new THREE.SphereGeometry(1,24,14),white,[x+.13,.08,z],[.18,.075,.13]);}
function tail(b,L){if(b.tail==='nub'){add(new THREE.SphereGeometry(1,24,16),white,[-1.45*L,1.05,0],[.12,.08,.08]);return}const angle=b.tail==='straight'?1.3:.85;add(new THREE.CapsuleGeometry(.045,.58,8,18),white,[-1.48*L,1.28,0],[1,1,1],[0,0,-angle]);add(new THREE.SphereGeometry(1,16,10),white,[-1.78*L,1.62,0],[.055,.045,.045])}
function ears(b,L){[-1,1].forEach(s=>{if(b.ear==='up'){add(new THREE.ConeGeometry(.16,.5,28),white,[1.38*L,2.18,s*.22],[.8,1,.42],[s*.08,0,-.18])}else{add(new THREE.CapsuleGeometry(.09,.42,10,18),white,[1.43*L,1.63,s*.3],[.85,1,.55],[.42,0,s*.25])}})}
function head(b,L,W){add(new THREE.SphereGeometry(1,40,24),white,[1.52*L,1.72,0],[.42*b.head,.34*b.head,.31*b.head]);add(new THREE.SphereGeometry(1,32,18),white,[1.86*L,1.64,0],[.3*b.head,.17*b.head,.19*b.head]);add(new THREE.SphereGeometry(1,20,12),dark,[2.08*L,1.66,0],[.065,.045,.055]);[-1,1].forEach(s=>add(new THREE.SphereGeometry(1,18,10),dark,[1.67*L,1.82,s*.17*W],[.032,.032,.032]));add(new THREE.CapsuleGeometry(.13,.42,12,20),white,[1.16*L,1.43,0],[1.2,1,.95],[0,0,-.68]);ears(b,L)}
function anatomyLines(b,L,W){add(new THREE.CapsuleGeometry(.018,1.1,6,10),lineMat,[.1,1.37,0],[1,1,1],[0,0,1.57]);add(new THREE.CapsuleGeometry(.016,.55,6,10),lineMat,[.58*L,1.22,.32*W],[1,1,1],[.25,0,.45]);add(new THREE.CapsuleGeometry(.016,.48,6,10),lineMat,[-.78*L,1.12,.3*W],[1,1,1],[-.2,0,-.35])}
function garment(b,L,W,H){if(state.cloth==='none')return;const c=clothes[state.cloth][1],m=new THREE.MeshPhysicalMaterial({color:c,roughness:state.cloth==='rain'?.28:.58,clearcoat:state.cloth==='rain'?.7:.12});if(state.cloth==='harness'){add(new THREE.TorusGeometry(.45,.025,10,64),m,[.48*L,1.07,0],[1,.22,.9*W],[0,1.57,0]);add(new THREE.TorusGeometry(.48,.025,10,64),m,[-.38*L,1.02,0],[1,.22,.85*W],[0,1.57,0]);add(new THREE.CapsuleGeometry(.025,1.28,6,10),m,[.05,1.2,.36*W],[1,1,1],[0,1.57,1.57]);return}add(bodyGeometry(L*.72,W*1.05,H*.82),m,[-.08,.03,0],[1,1,1]);add(new THREE.TorusGeometry(.34,.028,10,64),dark,[.92*L,1.36,0],[1,.24,.92*W],[0,1.57,0]);if(state.cloth==='puffer')for(let i=-3;i<4;i++)add(new THREE.CapsuleGeometry(.018,.82,6,10),material(0x87352f),[i*.22*L,1.18,.39*W],[1,1,1],[0,0,1.57]);}
function buildDog(){dog.clear();const base=breeds[state.breed],b={...base,L:base.L*scale.L,W:base.W*scale.W,H:base.H*scale.H,leg:base.leg*scale.leg,head:base.head};add(bodyGeometry(b.L,b.W,b.H),white,[0,0,0],[1,1,1]);add(new THREE.SphereGeometry(1,36,20),white,[.62*b.L,1.24,.34*b.W],[.28,.32,.11]);add(new THREE.SphereGeometry(1,36,20),white,[-.78*b.L,1.12,.31*b.W],[.27,.28,.1]);head(b,b.L,b.W);limb(.58*b.L,.25*b.W,true,b);limb(.58*b.L,-.25*b.W,true,b);limb(-.7*b.L,.24*b.W,false,b);limb(-.7*b.L,-.24*b.W,false,b);tail(b,b.L);anatomyLines(b,b.L,b.W);garment(b,b.L,b.W,b.H);centerDog();badge.textContent=base.label+' · 解剖白模'}
function centerDog(){dog.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(dog),c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3());dog.position.x-=c.x;dog.position.y+=1.38-c.y;dog.position.z-=c.z;root.scale.setScalar(clamp(3.55/Math.max(s.x,s.y*1.18),.78,1.25))}
function makeSet(){setRoot.clear();const colors={studio:0xd0cec7,home:0xd8c6ae,grass:0xa9c69d,shop:0xdce3e5};scene.background=new THREE.Color(colors[state.scene]);const floor=add(new THREE.PlaneGeometry(9,6),material(state.scene==='grass'?0x688c58:state.scene==='home'?0xb89673:0xc4c2ba),[0,-.02,-.35],[1,1,1],[-Math.PI/2,0,0],setRoot);floor.receiveShadow=true;add(new THREE.CircleGeometry(1.5,72),new THREE.MeshBasicMaterial({color:0x000,transparent:true,opacity:.12,depthWrite:false}),[0,.012,0],[1.8,.55,1],[-Math.PI/2,0,0],setRoot);if(state.scene==='home'){add(new THREE.BoxGeometry(1,1,1),material(0x86624a),[-2.8,.48,-2],[2,.45,.5],[0,0,0],setRoot);add(new THREE.SphereGeometry(1,24,16),material(0x527c4e),[2.4,.75,-1.2],[.5,.5,.5],[0,0,0],setRoot)}if(state.scene==='shop')for(let i=0;i<5;i++)add(new THREE.BoxGeometry(1,1,1),material([0xb94b40,0x31586a,0xe6c62b,0xdca6ba,0xf0eee8][i]),[-1.8+i*.85,1.45,-2.4],[.32,.42,.04],[0,0,0],setRoot)}
function applySize(){scale={L:clamp(+back.value/32,.82,1.32),W:clamp(+chest.value/42,.82,1.25),H:clamp(+chest.value/42,.9,1.18),leg:clamp(+height.value/29,.78,1.25)};fit.textContent='推荐 '+(+chest.value<36?'S':+chest.value<50?'M':+chest.value<66?'L':'XL');buildDog()}
Object.entries(clothes).forEach(([k,v])=>clothGrid.insertAdjacentHTML('beforeend',`<button class="card ${k==='none'?'active':''}" data-cloth="${k}"><span class="sw" style="--sw:${v[1]}"></span><b>${v[0]}</b><small>${k==='none'?'查看白模':'3D 包覆预览'}</small></button>`));
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===b.dataset.tab))});$$('[data-breed]').forEach(b=>b.onclick=()=>{state.breed=b.dataset.breed;$$('[data-breed]').forEach(x=>x.classList.toggle('active',x===b));buildDog()});$$('[data-cloth]').forEach(b=>b.onclick=()=>{state.cloth=b.dataset.cloth;$$('[data-cloth]').forEach(x=>x.classList.toggle('active',x===b));buildDog()});$$('[data-scene]').forEach(b=>b.onclick=()=>{state.scene=b.dataset.scene;$$('[data-scene]').forEach(x=>x.classList.toggle('active',x===b));makeSet()});apply.onclick=applySize;reset.onclick=()=>{root.rotation.y=.35;camera.zoom=1;camera.updateProjectionMatrix()};
function layout(){const r=viewer.getBoundingClientRect(),aspect=r.width/r.height,span=3.08;camera.left=-span*aspect;camera.right=span*aspect;camera.top=span;camera.bottom=-span;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height,false)}
let drag=false,lastX=0,pinch=0;const dom=renderer.domElement;dom.addEventListener('pointerdown',e=>{drag=true;lastX=e.clientX;dom.setPointerCapture?.(e.pointerId)});dom.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lastX;lastX=e.clientX;root.rotation.y+=dx*.01});dom.addEventListener('pointerup',()=>drag=false);dom.addEventListener('pointercancel',()=>drag=false);dom.addEventListener('touchstart',e=>{if(e.touches.length===2)pinch=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)},{passive:true});dom.addEventListener('touchmove',e=>{if(e.touches.length===2){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);camera.zoom=clamp(camera.zoom+(d-pinch)*.004,.75,2.6);pinch=d;camera.updateProjectionMatrix()}},{passive:true});new ResizeObserver(layout).observe(viewer);makeSet();applySize();root.rotation.y=.35;layout();function loop(){requestAnimationFrame(loop);renderer.render(scene,camera)}loop();
})()