(async()=>{
  const res=await fetch('./src/v34.js?v=34-base',{cache:'no-store'});
  let src=await res.text();
  src=src.replaceAll('PetForm V34','PetForm V37');
  src=src.replaceAll('真实模型试衣间','模型数据贴身试衣间');
  src=src.replace("const MODEL_URL='./assets/models/corgi_HP.obj?v=34';","const MODEL_URL='./assets/models/corgi_HP.obj?v=37';");
  src=src.replace('衣服目前是 3D 预贴合壳，下一步可以替换成真实衣服 OBJ/GLB。','衣服会读取 OBJ 顶点轮廓，按身体截面生成贴合外壳。后续输入胸围、背长后可以继续校准衣服松量。');
  src=src.replace('真实模型版会先用 OBJ 的包围盒推算胸背比例；后续可以把胸围、背长映射到模型和衣服缩放。','当前版本会读取 OBJ 顶点截面来生成衣服。后续这里会加入胸围、颈围、背长、腹围输入，用来控制衣服松量和尺码推荐。');
  src=src.replace("const state={cloth:'none',scene:'studio'};","const state={cloth:'none',scene:'studio'};let modelSize=new THREE.Vector3(.421,.744,.999),bodyProfile=[];");
  const oldFit="function fitObject(obj){obj.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(obj),c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3());obj.position.sub(c);modelGroup.position.set(0,0,0);stageGroup.position.set(-.55,1.54,0);stageGroup.rotation.y=.35;const sc=2.72/Math.max(s.x,s.y*1.12,s.z);stageGroup.scale.setScalar(sc);clothesGroup.position.set(0,0,0);makeCloth();$('#badge').textContent='柯基 OBJ · 已加载真实模型'}";
  const newFit=`function collectBodyProfile(obj,center,size){
    const bins=44,rows=Array.from({length:bins},()=>({xs:[],ys:[]}));
    const zMin=-size.z*.32,zMax=size.z*.30,legCut=-size.y*.25;
    obj.traverse(n=>{if(!n.isMesh||!n.geometry?.attributes?.position)return;const a=n.geometry.attributes.position,p=new THREE.Vector3();for(let i=0;i<a.count;i++){p.fromBufferAttribute(a,i);p.sub(center);if(p.z<zMin||p.z>zMax||p.y<legCut)continue;const k=Math.max(0,Math.min(bins-1,Math.floor((p.z-zMin)/(zMax-zMin)*bins)));rows[k].xs.push(Math.abs(p.x));rows[k].ys.push(p.y)}});
    const fallback={z:0,rx:size.x*.45,cy:size.y*.04,ry:size.y*.23,top:size.y*.28,belly:-size.y*.18};
    const prof=rows.map((r,i)=>{if(r.xs.length<12||r.ys.length<12)return null;r.xs.sort((a,b)=>a-b);r.ys.sort((a,b)=>a-b);const q=(arr,t)=>arr[Math.max(0,Math.min(arr.length-1,Math.floor(arr.length*t)))];const top=q(r.ys,.92)+size.y*.018,belly=q(r.ys,.20)-size.y*.004;return{z:zMin+(i+.5)/bins*(zMax-zMin),rx:q(r.xs,.92)+size.x*.026,cy:(top+belly)/2,ry:Math.max(size.y*.055,(top-belly)/2),top,belly}});
    for(let i=0;i<prof.length;i++)if(!prof[i])prof[i]=prof[i-1]||prof.slice(i+1).find(Boolean)||fallback;
    for(let pass=0;pass<3;pass++)for(let i=1;i<prof.length-1;i++){prof[i]={z:prof[i].z,rx:(prof[i-1].rx+prof[i].rx*2+prof[i+1].rx)/4,cy:(prof[i-1].cy+prof[i].cy*2+prof[i+1].cy)/4,ry:(prof[i-1].ry+prof[i].ry*2+prof[i+1].ry)/4,top:(prof[i-1].top+prof[i].top*2+prof[i+1].top)/4,belly:(prof[i-1].belly+prof[i].belly*2+prof[i+1].belly)/4}}
    return prof
  }
  function fitObject(obj){obj.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(obj),c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3());modelSize=s.clone();bodyProfile=collectBodyProfile(obj,c,s);obj.position.sub(c);modelGroup.position.set(0,0,0);stageGroup.position.set(-.55,1.54,0);stageGroup.rotation.y=.35;const sc=2.72/Math.max(s.x,s.y*1.12,s.z);stageGroup.scale.setScalar(sc);clothesGroup.position.set(0,0,0);makeCloth();$('#badge').textContent='OBJ 顶点轮廓 · 衣服按模型贴合'} `;
  const oldCloth="function makeCloth(){clothesGroup.clear();if(state.cloth==='none')return;const color=cloths[state.cloth][1],m=new THREE.MeshPhysicalMaterial({color,roughness:state.cloth==='rain'?.28:.58,clearcoat:state.cloth==='rain'?.7:.12,side:THREE.DoubleSide});if(state.cloth==='harness'){const a=new THREE.Mesh(new THREE.TorusGeometry(.46,.025,10,72),m);a.position.set(.16,.04,0);a.rotation.y=Math.PI/2;a.scale.set(1,.36,.82);clothesGroup.add(a);const b=a.clone();b.position.x=-.38;clothesGroup.add(b);const strap=new THREE.Mesh(new THREE.CapsuleGeometry(.025,1.18,6,12),m);strap.position.set(-.12,.18,.36);strap.rotation.z=Math.PI/2;clothesGroup.add(strap);return}const shell=new THREE.Mesh(new THREE.SphereGeometry(1,48,24),m);shell.position.set(-.1,.1,0);shell.scale.set(.9,.36,.42);clothesGroup.add(shell);const collar=new THREE.Mesh(new THREE.TorusGeometry(.28,.028,12,72),mat(0x2b2926));collar.position.set(.62,.33,0);collar.rotation.y=Math.PI/2;collar.scale.set(1,.35,1);clothesGroup.add(collar);if(state.cloth==='puffer'){for(let i=-3;i<=3;i++){const rib=new THREE.Mesh(new THREE.CapsuleGeometry(.018,.78,6,10),mat(0x87352f));rib.position.set(i*.19,.16,.38);rib.rotation.z=Math.PI/2;clothesGroup.add(rib)}}if(state.cloth==='tee'){const sleeveL=new THREE.Mesh(new THREE.SphereGeometry(.18,24,12),m);sleeveL.position.set(.28,-.18,.36);sleeveL.scale.set(.7,.5,.35);clothesGroup.add(sleeveL);const sleeveR=sleeveL.clone();sleeveR.position.z=-.36;clothesGroup.add(sleeveR)}}";
  const newCloth=`function makeCloth(){
    clothesGroup.clear();if(state.cloth==='none')return;
    const color=cloths[state.cloth][1],loose=state.cloth==='rain'?.055:state.cloth==='puffer'?.075:state.cloth==='harness'?.035:.045;
    const clothMat=new THREE.MeshPhysicalMaterial({color,roughness:state.cloth==='rain'?.24:.55,clearcoat:state.cloth==='rain'?.75:.16,metalness:0,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-1});
    const seamMat=new THREE.MeshStandardMaterial({color:0x302c27,roughness:.7,side:THREE.DoubleSide});
    const stitchMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.6,transparent:true,opacity:.75});
    const prof=bodyProfile.length?bodyProfile:[{z:0,rx:modelSize.x*.45,cy:modelSize.y*.04,ry:modelSize.y*.23,top:modelSize.y*.28,belly:-modelSize.y*.18}];
    function pick(t){const x=t*(prof.length-1),i=Math.floor(x),f=x-i,a=prof[Math.max(0,Math.min(prof.length-1,i))],b=prof[Math.max(0,Math.min(prof.length-1,i+1))];return{z:a.z+(b.z-a.z)*f,rx:a.rx+(b.rx-a.rx)*f,cy:a.cy+(b.cy-a.cy)*f,ry:a.ry+(b.ry-a.ry)*f,top:a.top+(b.top-a.top)*f,belly:a.belly+(b.belly-a.belly)*f}}
    function shellGeo(t0,t1,cover=2.18,extra=loose){const segZ=42,segA=42,pos=[],norm=[],uv=[],idx=[];for(let iz=0;iz<=segZ;iz++){const t=t0+(t1-t0)*iz/segZ,p=pick(t);for(let ia=0;ia<=segA;ia++){const u=ia/segA,a=-cover+cover*2*u,side=Math.abs(Math.sin(a));const rx=p.rx+extra+modelSize.x*.015*side,ry=p.ry+extra*.72;pos.push(Math.sin(a)*rx,p.cy+Math.cos(a)*ry,p.z);norm.push(Math.sin(a),Math.cos(a),0);uv.push(u,iz/segZ)}}const row=segA+1;for(let iz=0;iz<segZ;iz++)for(let ia=0;ia<segA;ia++){const a=iz*row+ia,b=a+1,c=a+row,d=c+1;idx.push(a,c,b,b,c,d)}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('normal',new THREE.Float32BufferAttribute(norm,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(idx);g.computeVertexNormals();return g}
    function addShell(t0,t1,cover,extra){const mesh=new THREE.Mesh(shellGeo(t0,t1,cover,extra),clothMat);mesh.castShadow=true;mesh.receiveShadow=true;clothesGroup.add(mesh);return mesh}
    function ringAt(t,matr=seamMat,thick=.008,cover=2.18){const p=pick(t),pts=[];for(let i=0;i<=70;i++){const a=-cover+cover*2*i/70;pts.push(new THREE.Vector3(Math.sin(a)*(p.rx+loose),p.cy+Math.cos(a)*(p.ry+loose*.72),p.z))}const curve=new THREE.CatmullRomCurve3(pts);const tube=new THREE.Mesh(new THREE.TubeGeometry(curve,70,thick,8,false),matr);tube.castShadow=true;clothesGroup.add(tube);return tube}
    if(state.cloth==='harness'){ringAt(.20,clothMat,.012,2.33);ringAt(.70,clothMat,.012,2.28);for(const u of [.28,.5,.72]){const pts=[];for(let i=0;i<prof.length;i++){const p=pick(i/(prof.length-1)),x=(u-.5)*2*(p.rx+loose*.8);pts.push(new THREE.Vector3(x,p.cy+p.ry*.78,p.z))}const strap=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),80,.01,8,false),clothMat);clothesGroup.add(strap)}return}
    if(state.cloth==='tee'){addShell(.17,.70,2.08,loose*.82);ringAt(.17,seamMat,.007,2.05);ringAt(.70,seamMat,.007,2.05)}
    else if(state.cloth==='vest'){addShell(.12,.76,2.18,loose);ringAt(.12,seamMat,.009,2.16);ringAt(.76,seamMat,.009,2.16)}
    else if(state.cloth==='rain'){addShell(.08,.86,2.28,loose);ringAt(.08,seamMat,.008,2.22);ringAt(.86,seamMat,.008,2.22)}
    else if(state.cloth==='puffer'){addShell(.10,.80,2.22,loose);for(let t=.18;t<.78;t+=.10)ringAt(t,new THREE.MeshStandardMaterial({color:0x7d332f,roughness:.65}),.006,2.18)}
    const topPts=[];for(let i=0;i<prof.length;i++){const t=i/(prof.length-1);if(t<.12||t>.78)continue;const p=pick(t);topPts.push(new THREE.Vector3(0,p.top+loose*.55,p.z))}if(topPts.length>2){const spine=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(topPts),80,.006,8,false),stitchMat);clothesGroup.add(spine)}
  }`;
  if(!src.includes(oldCloth)||!src.includes(oldFit))throw new Error('V37 patch failed: base changed');
  src=src.replace(oldCloth,newCloth).replace(oldFit,newFit);
  new Function(src)();
})().catch(e=>{document.querySelector('#app').innerHTML='<main style="min-height:100vh;display:grid;place-items:center;padding:24px;font-family:system-ui;color:#333;background:#f7f4ed;text-align:center">V37 加载失败<br><small>'+String(e.message||e)+'</small></main>'});
